entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

ping: {}

api:
  dashboard: true
  insecure: true

log:
  filePath: "/var/log/traefik/traefik.log"
  level: ERROR

accessLog:
  filePath: "/var/log/traefik/traefik-access.log"
  bufferingSize: 100

providers:
  docker:
    swarmMode: true
    swarmModeRefreshSeconds: 30