version: '3.9'

services:
  app:
    image: traefik:v2.10.4
    ports:
      - '80:80'
      - '443:443'
    # - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $(pwd)/traefik.yml:/etc/traefik/traefik.yml:ro
      - $(pwd)/traefik_log:/var/log/traefik
    networks:
      - traefik-net
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--tries=1',
          '--spide',
          '--no-check-certificate',
          '--no-verbose',
          'http://localhost:8080/ping'
        ]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 10s
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 10s
      resources:
        limits:
          cpus: '2.0'
          memory: 512M

networks:
  traefik-net:
    name: traefik-net
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/28
